package io.github.sd155.aiadvent3.chat.domain.providers.cloudru

import ai.koog.prompt.executor.clients.openai.base.models.OpenAIBaseLLMRequest
import ai.koog.prompt.executor.clients.openai.base.models.OpenAIBaseLLMResponse
import ai.koog.prompt.executor.clients.openai.base.models.OpenAIBaseLLMStreamResponse
import ai.koog.prompt.executor.clients.openai.base.models.OpenAIMessage
import ai.koog.prompt.executor.clients.openai.base.models.OpenAIResponseFormat
import ai.koog.prompt.executor.clients.openai.base.models.OpenAIStaticContent
import ai.koog.prompt.executor.clients.openai.base.models.OpenAITool
import ai.koog.prompt.executor.clients.openai.base.models.OpenAIToolCall
import ai.koog.prompt.executor.clients.openai.base.models.OpenAIToolChoice
import ai.koog.prompt.executor.clients.openai.base.models.OpenAIUsage
import ai.koog.prompt.executor.clients.serialization.AdditionalPropertiesFlatteningSerializer
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonElement

/**
 * Cloud.ru Chat Completions API Request
 * https://cloud.ru/docs/foundation-models/ug/topics/api-ref__specs?source-platform=#tag/Chat-Completions
 *
 */
@Serializable
internal class CloudruChatCompletionRequest(
    val messages: List<OpenAIMessage> = emptyList(),
    val prompt: String? = null,
    override val model: String? = null,
    override val stream: Boolean? = null,
    override val temperature: Double? = null,
    val tools: List<OpenAITool>? = null,
    val toolChoice: OpenAIToolChoice? = null,
    override val topP: Double? = null,
    override val topLogprobs: Int? = null,
    val maxTokens: Int? = null,
    val frequencyPenalty: Double? = null,
    val presencePenalty: Double? = null,
    val responseFormat: OpenAIResponseFormat? = null,
    val stop: List<String>? = null,
    val logprobs: Boolean? = null,
    val seed: Int? = null,
    val topK: Int? = null,
    val repetitionPenalty: Double? = null,
    val logitBias: Map<Int, Double>? = null,
    val minP: Double? = null,
    val topA: Double? = null,
    val prediction: OpenAIStaticContent? = null,
    val transforms: List<String>? = null,
    val models: List<String>? = null,
    val route: String? = null,
    val user: String? = null,
    val additionalProperties: Map<String, JsonElement>? = null,
) : OpenAIBaseLLMRequest

/**
 * Chat completion choice
 *
 * @property finishReason The reason the model stopped generating tokens.
 * This will be `stop` if the model hit a natural stop point or a provided stop sequence,
 * `length` if the maximum number of tokens specified in the request was reached,
 * `content_filter` if content was omitted due to a flag from our content filters,
 * `tool_calls` if the model called a tool, or `function_call` (deprecated) if the model called a function.
 * `error` if the model finishes the request with an error.
 * @property nativeFinishReason The raw finish_reason string returned by the model
 * @property message A chat completion message generated by the model.
 * @property error An error response structure typically used for conveying error details to the clients.
 *
 * See (CompletionsResponse Format)[https://cloud.ru/docs/foundation-models/ug/topics/api-ref__specs?source-platform=#tag/Chat-Completions]
 */
@Serializable
internal class CloudruChoice(
    val finishReason: String? = null,
    val nativeFinishReason: String? = null,
    val message: OpenAIMessage,
    val error: CloudruErrorResponse? = null
)

/**
 * Chat completion choice
 *
 * @property finishReason The reason the model stopped generating tokens.
 * This will be `stop` if the model hit a natural stop point or a provided stop sequence,
 * `length` if the maximum number of tokens specified in the request was reached,
 * `content_filter` if content was omitted due to a flag from our content filters,
 * `tool_calls` if the model called a tool, or `function_call` (deprecated) if the model called a function.
 * `error` if the model finishes the request with an error.
 * @property nativeFinishReason The raw finish_reason string returned by the model
 * @property delta A chat completion delta generated by streamed model responses.
 * @property error An error response structure typically used for conveying error details to the clients.
 *
 * See (CompletionsResponse Format)[https://cloud.ru/docs/foundation-models/ug/topics/api-ref__specs?source-platform=#tag/Chat-Completions]
 */
@Serializable
internal class CloudruStreamChoice(
    val finishReason: String? = null,
    val nativeFinishReason: String? = null,
    val delta: CloudruStreamDelta,
    val error: CloudruErrorResponse? = null
)

/**
 * @property content The contents of the chunk message.
 * @property role The role of the author of this message.
 * @property toolCalls The tool calls requested by the model.
 */
@Serializable
internal class CloudruStreamDelta(
    val content: String? = null,
    val role: String? = null,
    val toolCalls: List<OpenAIToolCall>? = null
)

/**
 * Represents an error response structure typically used for conveying error details to the clients.
 *
 * @property code The numeric code representing the error.
 * @property message A descriptive message providing details about the error.
 * @property metadata Optional additional information about the error in the form of key-value pairs.
 */
@Serializable
internal class CloudruErrorResponse(
    val code: Int,
    val message: String,
    val metadata: Map<String, String>? = null,
)

/**
 * Cloud.ru Chat Completion Response
 * See (CompletionsResponse Format)[https://cloud.ru/docs/foundation-models/ug/topics/api-ref__specs?source-platform=#tag/Chat-Completions]
 */
@Serializable
internal class CloudruChatCompletionResponse(
    val choices: List<CloudruChoice>,
    override val created: Long,
    override val id: String,
    override val model: String,
    val systemFingerprint: String? = null,
    @SerialName("object")
    val objectType: String = "chat.completion",
    val usage: OpenAIUsage? = null,
) : OpenAIBaseLLMResponse

/**
 * Cloud.ru Chat Completion Streaming Response
 * See (CompletionsResponse Format)[https://cloud.ru/docs/foundation-models/ug/topics/api-ref__specs?source-platform=#tag/Chat-Completions]
 */
@Serializable
internal class CloudruChatCompletionStreamResponse(
    val choices: List<CloudruStreamChoice>,
    override val created: Long,
    override val id: String,
    override val model: String,
    val systemFingerprint: String? = null,
    @SerialName("object")
    val objectType: String = "chat.completion.chunk",
    val usage: OpenAIUsage? = null,
) : OpenAIBaseLLMStreamResponse

internal object CloudruChatCompletionRequestSerializer :
    AdditionalPropertiesFlatteningSerializer<CloudruChatCompletionRequest>(CloudruChatCompletionRequest.serializer())
